BTC/USD:
  price_levels:
    - price: 104000
      condition: above
    - price: 101000
      condition: below
  percentage_changes:
    - percentage: 2
      timeframe: 30
  volatility:
    - threshold: 2
      timeframe: 5

PEPE/USD:
  price_levels:
    - price: 0.00001400
      condition: above
    - price: 0.00001280
      condition: below
  percentage_changes:
    - percentage: 2
      timeframe: 30
  volatility:
    - threshold: 2
      timeframe: 5