BTC/USD:
  price_levels:
    - price: 113000
      condition: above
      cooldown: 1800  # breakout signal
    - price: 110500
      condition: below
      cooldown: 1800  # failed breakout/fakeout
    - price: 109000
      condition: below
      cooldown: 3600  # deeper pullback zone
  percentage_changes:
    - percentage: 1.2
      timeframe: 15
      cooldown: 1800
    - percentage: 2.0
      timeframe: 30
      cooldown: 1800
    - percentage: 3.0
      timeframe: 60
      cooldown: 3600
  volatility:
    - threshold: 1.5
      timeframe: 15
      cooldown: 1800
    - threshold: 2.5
      timeframe: 60
      cooldown: 3600

PEPE/USD:
  price_levels:
    - price: 0.00001475
      condition: above
      cooldown: 1800  # confirmed breakout
    - price: 0.00001420
      condition: below
      cooldown: 1800  # potential fakeout or bull trap
    - price: 0.00001380
      condition: below
      cooldown: 3600  # structural breakdown
  percentage_changes:
    - percentage: 4
      timeframe: 15
      cooldown: 1800
    - percentage: 6
      timeframe: 30
      cooldown: 1800
    - percentage: 8
      timeframe: 60
      cooldown: 3600
  volatility:
    - threshold: 3.5
      timeframe: 15
      cooldown: 1800
    - threshold: 6
      timeframe: 60
      cooldown: 3600
